image: node:8.11.4
clone:
  depth: full
pipelines:
  default:
    - step:
        name: Deploy to Heroku
        deployment: production
        caches:
          - node
        script: 
          - node --version
          - npm --version
          - npm install
          - npm run build
          - git push -f https://heroku:5e87b04f-9e94-4c70-857f-3dca03afc35d@git.heroku.com/spacexcalendar-v2.git HEAD
